
# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

experiment_name: skull_MMD

# environment/computational parameters
seed: 123
device: cuda
num_workers: 4

# dataset parameters
src_train: C:/Users/blair/OneDrive - UBC/Skulls/traintex_split1.5
src_val: C:/Users/blair/OneDrive - UBC/Skulls/traintex_split2
target_train: C:/Users/blair/OneDrive - UBC/Skulls/test_split1.5
target_val: C:/Users/blair/OneDrive - UBC/Skulls/test_split2
target_eval: C:/Users/blair/OneDrive - UBC/Skulls/testing-named
num_classes: 16

# training hyperparameters
image_size: [224, 224]
num_epochs: 100
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001

# Model save path
save_path: C:/Users/blair/OneDrive - UBC/Skull-Adapt/classifier/models