# -*- coding: utf-8 -*-
"""
Created on Mon Oct 23 17:26:39 2023

@author: blair
"""

experiment_name: render-image

# environment/computational parameters
seed: 35776248
device: cuda
num_workers: 4

# dataset parameters
data_root: C:/Users/blair/OneDrive - UBC/Skulls/traintex
test_root: C:/Users/blair/OneDrive - UBC/Skulls/testing-named
num_classes: 16

# training hyperparameters
image_size: [224, 224]
num_epochs: 100
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001